export const ADDTOCART = "ADD_TOCART";
export const ADDTOHEART = "ADD_TOHEART";
export const CLICKACCOUNT = "CLICK_ACCOUNT";
export const CLICKCART = "CLICK_CART";
export const CLICKHEART = "CLICK_HEART";
export const ACCOUNT = "ACCOUNT";
export const DELETECARTITEM = "DELETE_CART_ITEM";
export const DELETEHEARTITEM = "DELETE_HEART_ITEM";
export const DELETEALLHEART = "DELETE_ALL_HEART";

export const SHOPPINGCART = 'SHOPPING_CART';
export const DELETESHOPCARTDATA = 'DELETE_SHOP_CARTDATA'
export const INCREASEQUANTITY = 'INCREASE_QUANTITY';
export const DECREASEQUANTITY = 'DECREASE_QUANTITY';
